### PR TITLE
select intermediate destination of CompositionMap based on input

### PR DESCRIPTION
**Pull request by kose-y**
I was trying to use `LinearMap` with a CuArray, and this issue blocked me.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Thanks, this LGTM. While you're at it, could you please also replace the two `Array` constructors in `kronecker.jl`, lines 109-110?

**Comment by kose-y** [comment]
Sure.

**Comment by dkarrasch** [comment]
Thanks once more. Now I realize that we may actually not need the `T = eltype(y)`/`Ty = eltype(y)` stuff (in both cases), since the default is `y`'s eltype anyway. Could you please remove them?

**Comment by dkarrasch** [comment]
Many thanks for your contribution. I'll release this soonish after #72 is merged as v2.6.

**Comment by Jutho** [comment]
Much better indeed, thanks.

**Pull request merged**
