### PR TITLE
Fallback options when complement function is not available

### PR DESCRIPTION
**Pull request by shivin9**
@Jutho A complement function is not always available, so in case we want to find out the inverse mapping then that is done by multiplying the linear map's complement with the vector. ie'`full(L)'*x`

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can this get reviewed? Something like this is necessary for full usage with IterativeSolvers.jl

**Comment by Jutho** [comment]
Is this really a good strategy? For large problems, generating the full matrix might just be to memory costly. Furthermore, with this approach, it is regenerated for every single application of At_mul_B and friends, which is highly inefficient.

I think it is better to error out in this case, so that the user knows he explicitly also has to define a transpose function, in order to be able to use it with e.g. an iterative solver that requires the transpose action. Any thoughts?

**Comment by shivin9** [comment]
Well many a times it's not that straight forward to write the transpose function and if the user wants to calculate the complement anyhow, then it can helpful if we give him an option. They are used quite frequently in iterative algorithms.
I will optimize it out soon btw.

**Comment by Jutho** [comment]
I still think this is not the way to go. In particular, you now always allocate a matrix zeros(T,M,N) when `fc` is not provided. This is too costly; one of the main points of `LinearMaps` is to represent operators which are too costly to store as a matrix.

**Comment by Jutho** [comment]
As a function? I wouldn't know how to do it. For the solution you were using above, I think you can just replace `LinearMap(f)` with `full(LinearMap(f))` wherever you are using it. Then the linear solver will be able to use the transpose, just because it has the full matrix.

**Comment by ChrisRackauckas** [comment]
That's a good point. So it's probably better to let the user `full` and just let it error if no complement is given. If there was a `sparse` function that would probably be the best option. Of course, if there's a way to construct the transposed operation that would be ideal, but whether it's possible eludes me.

**Pull request closed without merging**
