### PR TITLE
Fix index in BlockMap adjoint/transpose multiply

### LINKED ISSUE #58: hvcat indexing issue with misaligned blocks
While doing more thorough testing of `LinearMapsAA` I uncovered this issue with the new blockmap features (that are otherwise working great):

```
A = LinearMap(ones(3,2))
B = [I A; A I]
Matrix(B) # works fine
Matrix(B') # fails with error DimensionMismatch("mul!")
```

Now, one could argue that the way `B` is constructed in this MWE, with blocks that do not quite line up, is not the way we write block matrices in math, and I agree.  But that type of `hvcat` works fine with ordinary arrays, because the two block rows have the same number of columns.  I'm not sure it is worth trying to support multiplication with such constructs.  Perhaps `LinearMaps.hvcat` could just throw an error saying that such constructions are unsupported, e.g., by checking that all blocks in a given column have the same number of columns.

### PR DESCRIPTION
**Pull request by JeffFessler**
Fixes #58.

runtests needs additional tests such as:

```
A = LinearMap(ones(3,2))
B = [I A; A I]
@test Matrix(B') == Matrix(B)'
@test Matrix(transpose(B)) == Matrix(B)'
@test Matrix(adjoint(B)) == Matrix(B)'
```

### CODE REVIEW

**Comment by JeffFessler** [comment]
For future reference: `hvcat` works row-wise and there is no corresponding `vhcat` but the transpose of a `hvcat` is akin to what a hypothetical `vhcat` would make.
All of the existing nice indexing for row and column pieces works fine for the transpose.

**Comment by JeffFessler** [comment]
The failing tests seem to be 1.3 related.  I tested only with 1.1 locally before submitting the PR.

**Comment by dkarrasch** [comment]
Awesome, nice catch! Could you please add the proposed test at the end of the `hvcat` test section? The test failure is indeed related to the update by the 5-arg `mul!`. We can merge this with the test, and afterwards take care of adding version restrictions.

**Comment by JeffFessler** [comment]
Done.  I think...

**Pull request merged**
