### PR TITLE
Fast function map

### PR DESCRIPTION
**Pull request by LMescheder**
This pull request makes linear mappings type stable in julia 0.5 and when using the [Fast Anonymous](https://github.com/timholy/FastAnonymous.jl) package.
In order to do so, it splits the current `FunctionMap` type into `FunctionMap` and `MutatingFunctionMap` with common parent `AbstractFunctionMap`. This allows to use dispatch to chose the right multiplication method.
Contrary to the current solution, `issym` and `ishermitian` is only employed when `ftranspose` and `ctranspose` are not set. This was necessary to enforce type stability, but I believe it is also quite sensible.

### CODE REVIEW

**Comment by Jutho** [comment]
Thanks for this. I'll try to make some time to review as soon as possible. LinearMaps.jl has not received any major update since its initial release which was written for julia 0.3, only a small compatibility update for 0.4. So this is very welcome.

**Comment by Jutho** [comment]
I am sorry but this has slipped my mind. I did some updates to LinearMaps.jl (master) today, to make it compatible with v0.5. The biggest change involves replacing `issym` with `issymmetric` everywhere. Would you mind rebasing this PR?

**Comment by ChrisRackauckas** [comment]
FastAnonymous shouldn't be necessary with v0.5 since anonymous functions are generic. Since v0.5 is now required, should this be closed?

**Comment by Jutho** [comment]
I think LinearMaps.jl has received updates that are in line with the idea of this PR. Unless there are further questions or suggestions, I will close this PR.

**Pull request closed without merging**
