### PR TITLE
Construct sparse matrix from LinearMap

### PR DESCRIPTION
**Pull request by samuelpowell**
Could pre-allocate a vector for use constructing `Js` if that would be preferable.

### CODE REVIEW

**Comment by Jutho** [comment]
Looks good. As I never use sparse arrays (in the traditional sense), I haven't been following discussions in Julia Base closely. Do you know what the faith of sparse arrays and the corresponding constructors will be? Will `Base.sparse` still be a method in the upcoming 0.7/1.0-prerelease ?

**Comment by samuelpowell** [comment]
Hi @Jutho, The `Base.sparse` constructor used here is fairly fundamental (takes the `COO` form and converts to `CSC` format), and I can see no evidence of any pending changes. The deprecation of `full` et al. will need changes to the test (but then that applies to the dense array methods as well).

Having thought about this I could actually use the inner `SparseMatrixCSC` which would be more efficient (and is as low level as it gets). Will push some changes shortly.

**Comment by samuelpowell** [comment]
I have updated to build the CSC vectors directly. This is faster and involves fewer allocations. Added a test where there is actually some sparsity!

**Comment by Jutho** [comment]
Thanks for this!

**Comment by samuelpowell** [comment]
My pleasure, an extremely useful package @Jutho.

**Pull request merged**
